s = set()

no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))
no = input("Enter a number: ")
s.add(int(no))

print(s)